baseURL = "https://windstrap.netlify.app"
title = "Windstrap"

languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
pygmentsUseClasses=true

[params]
  author = "Praveen Juge"
  sitename = "Windstrap"
  image = "/brand/og.png"
  description = "Tailwind CSS with Bootstrap JS"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false